/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.32
 * Generated at: 2013-01-24 19:05:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class shiatsuInicio_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ff_005fview_0026_005flocale;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ff_005floadBundle_0026_005fvar_005fbasename_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005fform_0026_005fid;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005foutputText_0026_005fvalue_005fstyleClass_005fid_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005foutputText_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005foutputText_0026_005fvalue_005fstyleClass_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ff_005fview_0026_005flocale = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ff_005floadBundle_0026_005fvar_005fbasename_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005fform_0026_005fid = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005foutputText_0026_005fvalue_005fstyleClass_005fid_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005foutputText_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005foutputText_0026_005fvalue_005fstyleClass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ff_005fview_0026_005flocale.release();
    _005fjspx_005ftagPool_005ff_005floadBundle_0026_005fvar_005fbasename_005fnobody.release();
    _005fjspx_005ftagPool_005fh_005fform_0026_005fid.release();
    _005fjspx_005ftagPool_005fh_005foutputText_0026_005fvalue_005fstyleClass_005fid_005fnobody.release();
    _005fjspx_005ftagPool_005fh_005foutputText_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fh_005foutputText_0026_005fvalue_005fstyleClass_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 4.0 Transitional//EN\"\r\n");
      out.write("\"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\" />\r\n");
      out.write("\r\n");
      out.write("<!-- saved from url=(0014)about:internet -->\r\n");
      out.write("\r\n");
      out.write("<html lang=\"es\"><!-- InstanceBegin template=\"/Templates/plantilla.dwt\" codeOutsideHTMLIsLocked=\"false\" -->\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width\"/>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\"         content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("    <meta http-equiv=\"Content-Style-Type\"   content=\"text/css\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\"      content=\"IE=EmulateIE7\"/> \r\n");
      out.write("\t<!-- InstanceBeginEditable name=\"doctitle\" -->\r\n");
      out.write("<title>Shiatsu - Inicio </title>\r\n");
      out.write("<!-- InstanceEndEditable --> \r\n");
      out.write("\t\r\n");
      out.write("\t \r\n");
      out.write("\t \r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <link href=\"html5/normalize.css\"                rel=\"stylesheet\" type=\"text/css\" /> \r\n");
      out.write("    <link href=\"html5/plantilla_html5.css\"          rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("    <link href=\"theme/hmenu/src/skin-modern3.css\"   rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("    <link href=\"theme/styles/SIGETR.css\"            rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("    <link href=\"theme/styles/shiatzu.css\"              rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("    <link href=\"theme/styles/menu.css\"              rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("    <link href=\"theme/styles/stylesheet.css\"        rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("    <link href=\"theme/styles/tablas.css\"            rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("    <link href=\"theme/stylesheet.css\"               rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("    <link href=\"theme/tabpanel.css\"                 rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("    <link href=\"theme/Master.css\"                   rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\" src=\"html5/jquery.js\"></script> \r\n");
      out.write("    <script type=\"text/javascript\" src=\"html5/plantilla_html5.js\"></script> \r\n");
      out.write("    <script type=\"text/javascript\" src=\"theme/hmenu/src/hmenu.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">document.writeln(\"<style type='text/css'>#menu { display: none; }</style>\");</script>    \r\n");
      out.write("</head> \r\n");
      out.write("\r\n");
      if (_jspx_meth_f_005fview_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!-- InstanceEnd --></html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_f_005fview_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:view
    org.apache.myfaces.taglib.core.ViewTag _jspx_th_f_005fview_005f0 = (new org.apache.myfaces.taglib.core.ViewTag());
    _jsp_instancemanager.newInstance(_jspx_th_f_005fview_005f0);
    _jspx_th_f_005fview_005f0.setPageContext(_jspx_page_context);
    _jspx_th_f_005fview_005f0.setParent(null);
    // /shiatsuInicio.jsp(41,0) name = locale type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_f_005fview_005f0.setLocale(new org.apache.jasper.el.JspValueExpression("/shiatsuInicio.jsp(41,0) 'es-CR'",_el_expressionfactory.createValueExpression("es-CR",java.lang.Object.class)));
    _jspx_th_f_005fview_005f0.setJspId("jsp_846682760_0");
    int _jspx_eval_f_005fview_005f0 = _jspx_th_f_005fview_005f0.doStartTag();
    if (_jspx_eval_f_005fview_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_f_005fview_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_f_005fview_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_f_005fview_005f0.doInitBody();
      }
      do {
        out.write("\r\n");
        out.write("    ");
        if (_jspx_meth_f_005floadBundle_005f0(_jspx_th_f_005fview_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("        <body onload=\"DynarchMenu.setup('menu'); getFocus();\">\r\n");
        out.write("            <div id=\"wrap\"> \r\n");
        out.write("                <header id=\"tablaBanner\">\r\n");
        out.write("                </header>\r\n");
        out.write("                <nav>\r\n");
        out.write("                    ");
        if (_jspx_meth_h_005fform_005f0(_jspx_th_f_005fview_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("                </nav>\r\n");
        out.write("                <section id=\"main\"> \r\n");
        out.write("                    <div id=\"titulo\" class=\"Tit_04_naranja\">\r\n");
        out.write("\t\t\t\t\t<!-- InstanceBeginEditable name=\"titulo\" -->");
        if (_jspx_meth_h_005foutputText_005f2(_jspx_th_f_005fview_005f0, _jspx_page_context))
          return true;
        out.write("<!-- InstanceEndEditable -->\r\n");
        out.write("                    </div>\r\n");
        out.write("                    <div id=\"cuerpo\" class=\"Text\">\r\n");
        out.write("\t\t\t\t\t\t<!-- InstanceBeginEditable name=\"contenido\" --> \r\n");
        out.write("\t\t\t\t\t<!-- InstanceEndEditable -->   \r\n");
        out.write("                    </div>\r\n");
        out.write("                </section>\r\n");
        out.write("            </div>\r\n");
        out.write("            <div id=\"footer\">\r\n");
        out.write("                <footer>\r\n");
        out.write("                </footer>\r\n");
        out.write("            </div> \r\n");
        out.write("            <form method=\"post\" action=\"Templates/ibm_security_logout\" name=\"logout\" id=\"logout\">\r\n");
        out.write("                <input type=\"hidden\" name=\"logoutExitPage\" value=\"main.jsf\" />\r\n");
        out.write("            </form>   \r\n");
        out.write("        </body>\r\n");
        out.write("    ");
        int evalDoAfterBody = _jspx_th_f_005fview_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_f_005fview_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_f_005fview_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_f_005fview_005f0.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_f_005fview_005f0);
      return true;
    }
    _jspx_th_f_005fview_005f0.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_f_005fview_005f0);
    return false;
  }

  private boolean _jspx_meth_f_005floadBundle_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005fview_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:loadBundle
    org.apache.myfaces.taglib.core.LoadBundleTag _jspx_th_f_005floadBundle_005f0 = (org.apache.myfaces.taglib.core.LoadBundleTag) _005fjspx_005ftagPool_005ff_005floadBundle_0026_005fvar_005fbasename_005fnobody.get(org.apache.myfaces.taglib.core.LoadBundleTag.class);
    _jspx_th_f_005floadBundle_005f0.setPageContext(_jspx_page_context);
    _jspx_th_f_005floadBundle_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005fview_005f0);
    // /shiatsuInicio.jsp(42,4) name = var type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_f_005floadBundle_005f0.setVar("rcs");
    // /shiatsuInicio.jsp(42,4) name = basename type = javax.el.ValueExpression reqTime = false required = true fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_f_005floadBundle_005f0.setBasename(new org.apache.jasper.el.JspValueExpression("/shiatsuInicio.jsp(42,4) 'com.shiatsu.web.bundles.recursos'",_el_expressionfactory.createValueExpression("com.shiatsu.web.bundles.recursos",java.lang.String.class)));
    int _jspx_eval_f_005floadBundle_005f0 = _jspx_th_f_005floadBundle_005f0.doStartTag();
    if (_jspx_th_f_005floadBundle_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ff_005floadBundle_0026_005fvar_005fbasename_005fnobody.reuse(_jspx_th_f_005floadBundle_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ff_005floadBundle_0026_005fvar_005fbasename_005fnobody.reuse(_jspx_th_f_005floadBundle_005f0);
    return false;
  }

  private boolean _jspx_meth_h_005fform_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005fview_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:form
    org.apache.myfaces.taglib.html.HtmlFormTag _jspx_th_h_005fform_005f0 = (new org.apache.myfaces.taglib.html.HtmlFormTag());
    _jsp_instancemanager.newInstance(_jspx_th_h_005fform_005f0);
    _jspx_th_h_005fform_005f0.setPageContext(_jspx_page_context);
    _jspx_th_h_005fform_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005fview_005f0);
    // /shiatsuInicio.jsp(48,20) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_h_005fform_005f0.setId("formBanner");
    _jspx_th_h_005fform_005f0.setJspId("jsp_846682760_1");
    int _jspx_eval_h_005fform_005f0 = _jspx_th_h_005fform_005f0.doStartTag();
    if (_jspx_eval_h_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_h_005fform_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_h_005fform_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_h_005fform_005f0.doInitBody();
      }
      do {
        out.write("\r\n");
        out.write("                        \r\n");
        out.write("                            <div id=\"menus\">\r\n");
        out.write("                                <div id=\"usuario\" class=\"flotarIzquierda\"> \r\n");
        out.write("                                        ");
        if (_jspx_meth_h_005foutputText_005f0(_jspx_th_h_005fform_005f0, _jspx_page_context))
          return true;
        out.write("  \r\n");
        out.write("                                </div>\r\n");
        out.write("                                <div id=\"menu_fecha\" class=\"flotarDerecha\">\r\n");
        out.write("                                    <script language=\"JavaScript\">mostrarFecha();</script> - ");
        if (_jspx_meth_h_005foutputText_005f1(_jspx_th_h_005fform_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("                                </div> \r\n");
        out.write("                                <div id=\"menu_mes_contable\" class=\"flotarDerecha\">\r\n");
        out.write("                                    <label></label>  \r\n");
        out.write("                                </div>\r\n");
        out.write("                            </div>\r\n");
        out.write("                            <div style=\"clear: both\"></div>\r\n");
        out.write("                            <div id=\"raya_amarilla\"></div>\r\n");
        out.write("                            <div id=\"menu_page\">\r\n");
        out.write("\t\t\t\t\t\t\t\t<ul id=\"menu\">\t \r\n");
        out.write("\t\t\t\t\t\t\t\t<li><a href=\"shiatsuInicio.jsf?init=true\">Inicio</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t<li>Cat&aacute;logos\r\n");
        out.write("\t\t\t\t\t\t\t\t  <ul>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<li>Clientes\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  <ul>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"shiatsuActCliente.jsf?init=true\">Agregar</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"shiatsuConsClientes.jsf?init=true\">Consulta</a> </li> \r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"shiatsuListaClientes.jsf?init=true\">Mantenimiento</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  </ul>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<li>Diagn&oacute;stico\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  <ul>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"shiatsuActDiagnostico.jsf?init=true\">Agregar</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"shiatsuConsDiagnostico.jsf?init=true\">Consulta</a></li> \r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"shiatsuListaDiagnostico.jsf?init=true\">Mantenimiento</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  </ul>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<li>Enfermedad\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  <ul>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"shiatsuActEnfermedad.jsf?init=true\">Agregar</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"shiatsuConsEnfermedad.jsf?init=true\">Consulta</a></li> \r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"shiatsuListaEnfermedad.jsf?init=true\">Mantenimiento</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  </ul>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<li>Medicamento\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  <ul>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"shiatsuActMedicamaento.jsf?init=true\">Agregar</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"shiatsuConsMedicamento.jsf?init=true\">Consulta</a></li> \r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"shiatsuListaMedicamento.jsf?init=true\">Mantenimiento</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  </ul>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<li>Tipo Alopecia\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  <ul>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"shiatsuActTipoAlopecia.jsf?init=true\">Agregar</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"shiatsuConsTipoAlopecia.jsf?init=true\">Consulta</a></li> \r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"shiatsuListaTipoAlopecia.jsf?init=true\">Mantenimiento</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  </ul>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<li>Pa&iacute;s \r\n");
        out.write("\t\t\t\t\t\t\t\t\t  <ul>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"shiatsuActPais.jsf?init=true\">Agregar</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"shiatsuConsPais.jsf?init=true\">Consulta</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"shiatsuListaPais.jsf?init=true\">Mantenimiento</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  </ul>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t</li>  \r\n");
        out.write("\t\t\t\t\t\t\t\t\t<li>Profesi&oacute;n\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  <ul>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"shiatsuActProfesion.jsf?init=true\">Agregar</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"shiatsuConsProfesion.jsf?init=true\">Consulta</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"shiatsuListaProfesion.jsf?init=true\">Mantenimiento</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  </ul>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<li>Bodega\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  <ul>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"shiatsuActBodega.jsf?init=true\">Agregar</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"shiatsuConsBodega.jsf?init=true\">Consulta</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"shiatsuListaBodega.jsf?init=true\">Mantenimiento</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  </ul>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<li>Frecuencia Asistencia\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  <ul>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"shiatsuActFrecuenciaAsistencia.jsf?init=true\">Agregar</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"shiatsuConsFrecuenciaAsistencia.jsf?init=true\">Consulta</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"shiatsuListaFrecuenciaAsistencia.jsf?init=true\">Mantenimiento</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  </ul>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<li>Producto\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  <ul>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"shiatsuActProducto.jsf?init=true\">Agregar</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"shiatsuConsProducto.jsf?init=true\">Consulta</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"shiatsuListaProducto.jsf?init=true\">Mantenimiento</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  </ul>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<li>Droga\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  <ul>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"shiatsuActDroga.jsf?init=true\">Agregar</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"shiatsuConsDroga.jsf?init=true\">Consulta</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"shiatsuListaDroga.jsf?init=true\">Mantenimiento</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  </ul>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<li>TipoCliente\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  <ul>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"shiatsuActTipoCliente.jsf?init=true\">Agregar</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"shiatsuConsTipoCliente.jsf?init=true\">Consulta</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"shiatsuListaTipoCliente.jsf?init=true\">Mantenimiento</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  </ul>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<li>Suministro\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  <ul>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"shiatsuActSuministro.jsf?init=true\">Agregar</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"shiatsuConsSuministro.jsf?init=true\">Consulta</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"shiatsuListaSuministro.jsf?init=true\">Mantenimiento</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  </ul>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<li>Usuario\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  <ul>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"shiatsuActUsuario.jsf?init=true\">Agregar</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"shiatsuConsUsuario.jsf?init=true\">Consulta</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"shiatsuListaUsuario.jsf?init=true\">Mantenimiento</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  </ul>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
        out.write("\t\t\t\t\t\t\t\t  </ul>\r\n");
        out.write("\t\t\t\t\t\t\t\t</li>\r\n");
        out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Salir</a> </li>\r\n");
        out.write("\t\t\t\t\t\t\t  </ul> \r\n");
        out.write("                      </div> \r\n");
        out.write("                  ");
        int evalDoAfterBody = _jspx_th_h_005fform_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_h_005fform_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_h_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_h_005fform_005f0.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_h_005fform_005f0);
      return true;
    }
    _jspx_th_h_005fform_005f0.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_h_005fform_005f0);
    return false;
  }

  private boolean _jspx_meth_h_005foutputText_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputText
    org.apache.myfaces.taglib.html.HtmlOutputTextTag _jspx_th_h_005foutputText_005f0 = (new org.apache.myfaces.taglib.html.HtmlOutputTextTag());
    _jsp_instancemanager.newInstance(_jspx_th_h_005foutputText_005f0);
    _jspx_th_h_005foutputText_005f0.setPageContext(_jspx_page_context);
    _jspx_th_h_005foutputText_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f0);
    // /shiatsuInicio.jsp(52,40) name = styleClass type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_h_005foutputText_005f0.setStyleClass(new org.apache.jasper.el.JspValueExpression("/shiatsuInicio.jsp(52,40) 'outputText'",_el_expressionfactory.createValueExpression("outputText",java.lang.Object.class)));
    // /shiatsuInicio.jsp(52,40) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_h_005foutputText_005f0.setId("usuario");
    // /shiatsuInicio.jsp(52,40) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_h_005foutputText_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/shiatsuInicio.jsp(52,40) 'Shiatzu'",_el_expressionfactory.createValueExpression("Shiatzu",java.lang.Object.class)));
    _jspx_th_h_005foutputText_005f0.setJspId("jsp_846682760_2");
    int _jspx_eval_h_005foutputText_005f0 = _jspx_th_h_005foutputText_005f0.doStartTag();
    if (_jspx_th_h_005foutputText_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_h_005foutputText_005f0.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_h_005foutputText_005f0);
      return true;
    }
    _jspx_th_h_005foutputText_005f0.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_h_005foutputText_005f0);
    return false;
  }

  private boolean _jspx_meth_h_005foutputText_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputText
    org.apache.myfaces.taglib.html.HtmlOutputTextTag _jspx_th_h_005foutputText_005f1 = (new org.apache.myfaces.taglib.html.HtmlOutputTextTag());
    _jsp_instancemanager.newInstance(_jspx_th_h_005foutputText_005f1);
    _jspx_th_h_005foutputText_005f1.setPageContext(_jspx_page_context);
    _jspx_th_h_005foutputText_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f0);
    // /shiatsuInicio.jsp(55,93) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_h_005foutputText_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/shiatsuInicio.jsp(55,93) '#{rcs['version']}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"#{rcs['version']}",java.lang.Object.class)));
    _jspx_th_h_005foutputText_005f1.setJspId("jsp_846682760_3");
    int _jspx_eval_h_005foutputText_005f1 = _jspx_th_h_005foutputText_005f1.doStartTag();
    if (_jspx_th_h_005foutputText_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_h_005foutputText_005f1.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_h_005foutputText_005f1);
      return true;
    }
    _jspx_th_h_005foutputText_005f1.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_h_005foutputText_005f1);
    return false;
  }

  private boolean _jspx_meth_h_005foutputText_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005fview_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputText
    org.apache.myfaces.taglib.html.HtmlOutputTextTag _jspx_th_h_005foutputText_005f2 = (new org.apache.myfaces.taglib.html.HtmlOutputTextTag());
    _jsp_instancemanager.newInstance(_jspx_th_h_005foutputText_005f2);
    _jspx_th_h_005foutputText_005f2.setPageContext(_jspx_page_context);
    _jspx_th_h_005foutputText_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005fview_005f0);
    // /shiatsuInicio.jsp(175,49) name = styleClass type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_h_005foutputText_005f2.setStyleClass(new org.apache.jasper.el.JspValueExpression("/shiatsuInicio.jsp(175,49) 'outputText'",_el_expressionfactory.createValueExpression("outputText",java.lang.Object.class)));
    // /shiatsuInicio.jsp(175,49) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_h_005foutputText_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/shiatsuInicio.jsp(175,49) ''",_el_expressionfactory.createValueExpression("",java.lang.Object.class)));
    _jspx_th_h_005foutputText_005f2.setJspId("jsp_846682760_4");
    int _jspx_eval_h_005foutputText_005f2 = _jspx_th_h_005foutputText_005f2.doStartTag();
    if (_jspx_th_h_005foutputText_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_h_005foutputText_005f2.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_h_005foutputText_005f2);
      return true;
    }
    _jspx_th_h_005foutputText_005f2.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_h_005foutputText_005f2);
    return false;
  }
}
